"""
PDF rendering for AuditReport using fpdf2 (pure Python, no system deps).

Uses the built-in core fonts (Helvetica + Courier). Non-Latin-1 characters
are sanitized so the export never crashes on emoji or unicode-only sources.
"""
from io import BytesIO
from typing import List
from app.models.schemas import AuditReport, Finding


SEV_COLOR = {
    "critical": (220, 38, 38),    # red
    "high":     (234, 88, 12),    # orange
    "medium":   (202, 138, 4),    # yellow-700
    "low":      (37, 99, 235),    # blue
    "informational": (107, 114, 128),  # gray
}


def _safe(text: str) -> str:
    """fpdf2 core fonts use latin-1; strip the rest gracefully."""
    if text is None:
        return ""
    return text.encode("latin-1", "replace").decode("latin-1")


def render(report: AuditReport) -> bytes:
    try:
        from fpdf import FPDF  # fpdf2
    except ImportError as e:  # pragma: no cover
        raise RuntimeError(
            "fpdf2 is not installed. Add `fpdf2` to requirements.txt."
        ) from e

    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_title(_safe(f"Audit report - {report.meta.filename}"))
    pdf.set_creator("Smart Contract Auditor")

    # ── Cover ───────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(31, 41, 55)
    pdf.cell(0, 14, _safe("Smart Contract Audit Report"), ln=True)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(75, 85, 99)
    pdf.cell(0, 7, _safe(f"File: {report.meta.filename}"), ln=True)
    pdf.cell(0, 7, _safe(
        f"Contracts: {', '.join(report.meta.contracts) or 'unknown'}"
    ), ln=True)
    pdf.cell(0, 7, _safe(f"SLOC: {report.meta.sloc}"), ln=True)
    pdf.cell(0, 7, _safe(
        f"Detectors: {', '.join(report.meta.detectors_run)}"
    ), ln=True)
    pdf.cell(0, 7, _safe(f"Generated: {report.meta.timestamp}"), ln=True)
    pdf.cell(0, 7, _safe(f"Duration: {report.meta.duration_ms} ms"), ln=True)

    pdf.ln(6)
    _draw_summary_table(pdf, report)

    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(0, 5, _safe(
        "This report is generated by automated heuristic and static-"
        "analysis tooling. It is intended as a complement to, not a "
        "replacement for, professional manual review."
    ))

    # ── Findings ─────────────────────────────────────────────────────────────
    if not report.findings:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(22, 163, 74)
        pdf.cell(0, 10, _safe("No findings - clean run"), ln=True)
    else:
        for idx, finding in enumerate(report.findings, 1):
            _draw_finding(pdf, idx, finding)

    out = pdf.output(dest="S")
    if isinstance(out, str):  # fpdf2 returns str on older versions
        return out.encode("latin-1")
    if isinstance(out, (bytes, bytearray)):
        return bytes(out)
    # Fallback: BytesIO
    buf = BytesIO()
    buf.write(out)
    return buf.getvalue()


def _draw_summary_table(pdf, report: AuditReport) -> None:
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(0, 8, _safe("Severity summary"), ln=True)

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(243, 244, 246)
    pdf.set_text_color(31, 41, 55)

    headers = ("Severity", "Count")
    widths = (60, 30)
    for h, w in zip(headers, widths):
        pdf.cell(w, 8, _safe(h), border=1, align="L", fill=True)
    pdf.ln(8)

    pdf.set_font("Helvetica", "", 10)
    for sev in ("critical", "high", "medium", "low", "informational"):
        count = int(report.summary.get(sev, 0))
        r, g, b = SEV_COLOR[sev]
        pdf.set_text_color(r, g, b)
        pdf.cell(widths[0], 7, _safe(sev.capitalize()), border=1)
        pdf.set_text_color(31, 41, 55)
        pdf.cell(widths[1], 7, _safe(str(count)), border=1, align="R")
        pdf.ln(7)


def _draw_finding(pdf, idx: int, f: Finding) -> None:
    pdf.add_page()
    # Header bar
    r, g, b = SEV_COLOR.get(f.severity, (60, 60, 60))
    pdf.set_fill_color(r, g, b)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(35, 8, _safe(f" {f.severity.upper()}"),
             border=0, fill=True, align="L")
    pdf.set_text_color(255, 255, 255)
    pdf.set_fill_color(55, 65, 81)
    pdf.cell(35, 8, _safe(f" {f.detector}"), border=0, fill=True, align="L")
    pdf.cell(0, 8, "", ln=True)

    # Title
    pdf.set_text_color(17, 24, 39)
    pdf.set_font("Helvetica", "B", 13)
    pdf.ln(2)
    pdf.multi_cell(0, 7, _safe(f"{idx}. {f.title}"))

    # Location
    if f.line_start:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(107, 114, 128)
        loc = (f"line {f.line_start}"
               if not f.line_end or f.line_end == f.line_start
               else f"lines {f.line_start} - {f.line_end}")
        pdf.cell(0, 5, _safe(f"Location: {loc}"), ln=True)
        pdf.ln(2)

    # Description
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(31, 41, 55)
    pdf.multi_cell(0, 5, _safe(f.description))
    pdf.ln(2)

    # Code snippet
    if f.code_snippet:
        pdf.set_fill_color(243, 244, 246)
        pdf.set_font("Courier", "", 8)
        pdf.set_text_color(17, 24, 39)
        for line in f.code_snippet.splitlines()[:25]:  # cap to keep PDF small
            pdf.cell(0, 4, _safe(line[:120]), border=0, fill=True, ln=True)
        pdf.ln(2)

    # Recommendation
    if f.recommendation:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(22, 163, 74)
        pdf.cell(0, 6, _safe("Recommendation"), ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(31, 41, 55)
        pdf.multi_cell(0, 5, _safe(f.recommendation))
        pdf.ln(1)

    # AI explanation
    if f.ai_explanation:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(99, 102, 241)
        pdf.cell(0, 6, _safe("AI Analysis"), ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(31, 41, 55)
        pdf.multi_cell(0, 5, _safe(f.ai_explanation))
        pdf.ln(1)

    # References
    if f.references:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(75, 85, 99)
        pdf.cell(0, 6, _safe("References"), ln=True)
        pdf.set_font("Helvetica", "", 9)
        for ref in f.references:
            pdf.set_text_color(99, 102, 241)
            pdf.cell(0, 5, _safe(f"- {ref}"), ln=True)
